services:
  - type: web
    name: felicity-backend-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: "7d"
      - key: ADMIN_EMAIL
        value: "admin@felicity.iiit.ac.in"
      - key: ADMIN_PASSWORD
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_SECURE
        value: "false"
      - key: EMAIL_USER
        value: "felicity7284@gmail.com"
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: "Felicity <felicity7284@gmail.com>"
      - key: EMAIL_FROM_NAME
        value: "Felicity"
      - key: EMAIL_REPLY_TO
        value: "felicity7284@gmail.com"
      - key: FRONTEND_URL
        value: "https://felicity-event-mgmt.netlify.app"
      - key: API_URL
        value: "https://felicity-backend-api.onrender.com"
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: "us-east-1"
